### ISSUE TITLE
Failed to scan (internal class) "This feature requires ASM7"

### ISSUE THREAD

**Issue by msgilligan** [beryx/badass-jlink-plugin#123]
Trying to run JLink on a JAR that was built using JDK 11 and using `java.net.http` I get the following error: 

``` 
Failed to scan foundation/omni/rest/omniwallet/mjdk/OmniwalletModernJDKClient$UncheckedObjectMapper.class
 java.lang.UnsupportedOperationException: This feature requires ASM7
 	at org.beryx.jlink.shadow.asm.ClassVisitor.visitNestHost(ClassVisitor.java:150)
 	at org.beryx.jlink.shadow.asm.ClassReader.accept(ClassReader.java:550)
 	at org.beryx.jlink.shadow.asm.ClassReader.accept(ClassReader.java:400)
```

(Note: The error doesn't seem to stop the resulting app from running)

**Comment by siordache** [comment]
I upgraded to ASM8 in release 2.17.6. The error should no longer occur.
