### ISSUE TITLE
Jlink + Selenium 3.141.59 

### ISSUE THREAD

**Issue by alex5250** [beryx/badass-jlink-plugin#125]
I am using Selenium to build my software. Also when I try to build it it fails with mistake. 
Java 11.0.6 LTS AdoptOpenJDK .
OS Windows 10 
IDE : IdeaJ 2019.3.3
All permissions are set. 
Checked on Gradle 5.2.1 and 6.2.2

module.info.
```
module xxxxx.main {
    requires javafx.fxml;
    requires javafx.graphics;
    requires javafx.base;
    requires javafx.controls;
    requires selenium.api;
    requires selenium.firefox.driver;
    requires selenium.java;
    requires selenium.support;
    requires selenium.remote.driver;
    opens APP to javafx.fxml;
    exports APP;
}
```
Jlink Configuration
```
jlink {
    launcher {
        options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
        name = 'CoronaVirusCases'
        addExtraDependencies("javafx")
        addExtraDependencies("org.openqa.selenium.firefox")
        forceMerge "selenium"
    }
}
```

Checked on :
  'org.beryx.jlink' version '2.11.1'
  'org.beryx.jlink' version '2.16.2'
  'org.beryx.jlink' version '2.17.2'

When I try build it via gradle it gives me : 
```
`> Task :prepareMergedJarsDir FAILED
> Configure project :radle --stacktrace  jlink
FAILURE: Build failed with an exception.'
<=====--------> 44% EXECUTING [1s]
* What went wrong:rsDir
Execution failed for task ':prepareMergedJarsDir'.
> Could not copy zip entry C:\xxxx\build\jlinkbase\nonmodjars\selenium-remote-driver-3.141.5.jar!META-INF/versions/9/ to 'C:\xxx\build\jlinkbase\tmpjars\META-INF\versions\9'.
   > Cannot create directory 'C:\xxxx\build\jlinkbase\tmpjars\META-INF\versions\9' as it already exists, but is not a directory

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':prepareMergedJarsDir'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.GradleException: Could not expand ZIP 'C:\CoronaVirusCases\build\jlinkbase\nonmodjars\selenium-remote-driver-3.141.5.jar'.
        at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:110)
        at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:110)
        at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl.visit(AbstractFileTree.java:197)
        at org.gradle.api.internal.file.CompositeFileTree.visit(CompositeFileTree.java:93)
        at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpecActionImpl.java:40)
        at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpecActionImpl.java:24)
        at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecResolver.walk(DefaultCopySpec.java:702)
        at org.gradle.api.internal.file.copy.DefaultCopySpec.walk(DefaultCopySpec.java:497)
        at org.gradle.api.internal.file.copy.DelegatingCopySpecInternal.walk(DelegatingCopySpecInternal.java:282)
        at org.gradle.api.internal.file.copy.CopySpecBackedCopyActionProcessingStream.process(CopySpecBackedCopyActionProcessingStream.java:39)
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator.lambda$execute$1(DuplicateHandlingCopyActionDecorator.java:43)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator.lambda$execute$1(NormalizingCopyActionDecorator.java:60)
        at org.gradle.api.internal.file.copy.FileCopyAction.execute(FileCopyAction.java:38)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator.execute(NormalizingCopyActionDecorator.java:59)
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator.execute(DuplicateHandlingCopyActionDecorator.java:43)
        at org.gradle.api.internal.file.copy.CopyActionExecuter.execute(CopyActionExecuter.java:40)
        at org.gradle.api.internal.file.copy.FileCopier.doCopy(FileCopier.java:80)
        at org.gradle.api.internal.file.copy.FileCopier.copy(FileCopier.java:65)
        at org.gradle.api.internal.file.DefaultFileOperations.copy(DefaultFileOperations.java:207)
        at org.gradle.api.internal.project.DefaultProject.copy(DefaultProject.java:1092)
        at org.gradle.api.internal.project.DefaultProject.copy(DefaultProject.java:1087)
        at org.gradle.api.Project$copy.call(Unknown Source)
        at org.beryx.jlink.impl.PrepareMergedJarsDirTaskImpl$_mergeUnpackedContents_closure3.doCall(PrepareMergedJarsDirTaskImpl.groovy:76)
        at jdk.internal.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.beryx.jlink.impl.PrepareMergedJarsDirTaskImpl.mergeUnpackedContents(PrepareMergedJarsDirTaskImpl.groovy:74)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.beryx.jlink.impl.PrepareMergedJarsDirTaskImpl.execute(PrepareMergedJarsDirTaskImpl.groovy:44)
        at org.beryx.jlink.PrepareMergedJarsDirTask.createMergedModuleAction(PrepareMergedJarsDirTask.groovy:88)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:727)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:568)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:553)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:536)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:276)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:265)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:153)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:67)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:41)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:192)
        ... 30 more
Caused by: org.gradle.api.internal.file.AbstractFileTreeElement$CopyFileElementException: Could not copy zip entry C:\CoronaVirusCases\build\jlinkbase\nonmodjars\selenium-remote-driver-3.141.5.jar!META-INF/versions/9/ to 'C:\CoronaVirusCases\build\jlinkbase\tmpjars\META-INF\versions\9'.
        at org.gradle.api.internal.file.AbstractFileTreeElement.copyTo(AbstractFileTreeElement.java:88)
        at org.gradle.api.internal.file.copy.DefaultFileCopyDetails.copyTo(DefaultFileCopyDetails.java:123)
        at org.gradle.api.internal.file.copy.FileCopyAction$FileCopyDetailsInternalAction.processFile(FileCopyAction.java:49)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator.maybeVisit(NormalizingCopyActionDecorator.java:100)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator.lambda$execute$0(NormalizingCopyActionDecorator.java:67)
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator.lambda$execute$0(DuplicateHandlingCopyActionDecorator.java:65)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.processFile(CopyFileVisitorImpl.java:64)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.visitFile(CopyFileVisitorImpl.java:48)
        at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl$1.visitFile(AbstractFileTree.java:208)
        at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:103)
        ... 125 more
Caused by: org.gradle.api.UncheckedIOException: Cannot create directory 'C:\CoronaVirusCases\build\jlinkbase\tmpjars\META-INF\versions\9' as it already exists, but is not a directory
        at org.gradle.util.GFileUtils.mkdirs(GFileUtils.java:291)
        at org.gradle.api.internal.file.AbstractFileTreeElement.copyTo(AbstractFileTreeElement.java:80)
        ... 134 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 43s
4 actionable tasks: 1 executed, 3 up-to-date
```
IdeaJ Gives me :
```
Execution failed for task ':prepareMergedJarsDir'.
> Could not expand ZIP 'C:\Users\Alex\IdeaProjects\CoronaVirusCases\build\jlinkbase\nonmodjars\selenium-api-3.141.5.jar'.
```

           `

**Comment by siordache** [comment]
`selenium-remote-driver-3.141.59.jar` is broken. In `META-INF/versions` it contains both a directory and a regular file named `9`:

![image](https://user-images.githubusercontent.com/1158863/76873010-7dd42300-686d-11ea-8b5d-76be67cd3c76.png)

This causes Gradle's `ZipFileTree.visit()` method to fail. You need to fix the selenium-remote-driver JAR before executing the `prepareMergedJarsDir` task.

**Comment by alex5250** [comment]
All works . Thanks It was a problem .

**Comment by siordache** [comment]
@alex5250 Here a workaround for fixing the selenium JARs on-the-fly:

```
configurations {
    broken { extendsFrom implementation }
}


tasks.prepareMergedJarsDir.doFirst {
    configurations.broken.files.findAll { f ->
        f.name.startsWith "selenium"
    }.each { brokenJar ->
        def destDir = file("$buildDir/broken")
        delete destDir
        mkdir destDir

        def zt = zipTree(brokenJar).matching {
            exclude 'META-INF/versions/**'
        }
        def expandedPath = zt.fileTree.tree.mirror.dir.path
        def files = zt.files.each { f ->
            def pathInJar = (f.path - expandedPath).substring(1)
            def destFilePath = destDir.toPath().resolve(pathInJar)
            mkdir destFilePath.parent
            java.nio.file.Files.copy(f.toPath(), destFilePath)
        }

        delete brokenJar
        def jarExec = java.util.spi.ToolProvider.findFirst( "jar" ).get()
        def result = jarExec.run(System.out, System.err,
            '-cf', "$brokenJar.path", '-C', destDir.path, '.')
        println "Fixed $brokenJar"
    }
}
```

**Comment by alex5250** [comment]
Thanks .

**Comment by nucleate** [comment]
> @alex5250 Here a workaround for fixing the selenium JARs on-the-fly:
> 
> ```
> configurations {
>     broken { extendsFrom implementation }
> }
> 
> 
> tasks.prepareMergedJarsDir.doFirst {
>     configurations.broken.files.findAll { f ->
>         f.name.startsWith "selenium"
>     }.each { brokenJar ->
>         def destDir = file("$buildDir/broken")
>         delete destDir
>         mkdir destDir
> 
>         def zt = zipTree(brokenJar).matching {
>             exclude 'META-INF/versions/**'
>         }
>         def expandedPath = zt.fileTree.tree.mirror.dir.path
>         def files = zt.files.each { f ->
>             def pathInJar = (f.path - expandedPath).substring(1)
>             def destFilePath = destDir.toPath().resolve(pathInJar)
>             mkdir destFilePath.parent
>             java.nio.file.Files.copy(f.toPath(), destFilePath)
>         }
> 
>         delete brokenJar
>         def jarExec = java.util.spi.ToolProvider.findFirst( "jar" ).get()
>         def result = jarExec.run(System.out, System.err,
>             '-cf', "$brokenJar.path", '-C', destDir.path, '.')
>         println "Fixed $brokenJar"
>     }
> }
> ```

I have the same building issue. I've just used your solution, but it fails on line (def expandedPath = zt.fileTree.tree.mirror.dir.path) with message:
Execution failed for task ':prepareMergedJarsDir'.
> No such property: fileTree for class: org.gradle.api.internal.file.collections.FileTreeAdapter
  Possible solutions: asFileTree

Atfer this I changed zt.fileTree.* to zt.asFileTree and got another failed message in line (def destFilePath = destDir.toPath().resolve(pathInJar)):
Execution failed for task ':prepareMergedJarsDir'.
> Illegal char <:> at index 0: :\zoomaio\build\tmp\expandedArchives\selenium-java-3.141.59.jar_ca554a8fa5a80e39066d65f3fd614f36\META-INF\MANIFEST.MF
How can I solve it?

**Comment by siordache** [comment]
@nucleate  What version of Gradle do you use?

**Comment by nucleate** [comment]
@siordache 6.3

**Comment by siordache** [comment]
I cannot reproduce the issue on my machine, but maybe we can figure out what the problem is, by printing some info.  To do this, please insert a line throwing a GradleException in your build script, as shown below:

```
def expandedPath = zt.asFileTree.tree.mirror.dir.path
def files = zt.files.each { f ->
    def pathInJar = (f.path - expandedPath).substring(1)
    throw new GradleException("expandedPath: $expandedPath\nf.path=$f.path\npathInJar:$pathInJar")
    def destFilePath = destDir.toPath().resolve(pathInJar)
    mkdir destFilePath.parent
    java.nio.file.Files.copy(f.toPath(), destFilePath)
}
```

Then, post the error message here.

**Comment by nucleate** [comment]
@siordache 
Execution failed for task ':prepareMergedJarsDir'.
> expandedPath: D:\zoomaio\build\tmp\expandedArchives\selenium-java-3.141.59.jar_ca554a8fa5a80e39066d65f3fd614f36
  f.path=D:\zoomaio\build\tmp\expandedArchives\selenium-java-3.141.59.jar_ca554a8fa5a80e39066d65f3fd614f36\META-INF\MANIFEST.MF
  pathInJar:META-INF\MANIFEST.MF

**Comment by siordache** [comment]
Hmmm... I hoped to see some strange paths, but everything looks OK. So why does your build fail?
Let's try to use println instead of GradleException. Put this in your build script:
```
def files = zt.files.each { f ->
    def pathInJar = (f.path - expandedPath).substring(1)
    println "expandedPath: $expandedPath, f.path=$f.path, pathInJar:$pathInJar, destDir: $destDir"
    def destFilePath = destDir.toPath().resolve(pathInJar)
    mkdir destFilePath.parent
    java.nio.file.Files.copy(f.toPath(), destFilePath)
}
```

Now there will be a lot of output, but I'm interested only in the last few lines printed before your build crashes.

**Comment by nucleate** [comment]
@siordache 
expandedPath: D:\zoomaio\build\tmp\expandedArchives\selenium-api-3.141.59.jar_ca1b23fb9828af3b482957accf037f5e, f.path=D:\zoomaio\build\tmp\expandedArchives\selenium-api-3.141.59.jar_ca1
b23fb9828af3b482957accf037f5e\org\openqa\selenium\mobile\NetworkConnection.class, pathInJar:org\openqa\selenium\mobile\NetworkConnection.class, destDir: D:\zoomaio\build\broken
Fixed C:\Users\denis\.gradle\caches\modules-2\files-2.1\org.seleniumhq.selenium\selenium-api\3.141.59\e006ffd3aa7841e6e9125d9e6691b3a6b7592b05\selenium-api-3.141.59.jar
Excluding kotlin/native/concurrent/SharedImmutable.class from the merged module.
Excluding kotlin/native/concurrent/ThreadLocal.class from the merged module.

> Task :createMergedModule
Cannot derive uses clause from service loader invocation in: org/apache/commons/compress/utils/ServiceLoaderIterator.<init>().
D:\zoomaio\build\jlinkbase\tmpjars\zoomaio.merged.module\module-info.java:302: error: PatternCompiler is not public in com.google.common.base; cannot be accessed from outside package
    uses com.google.common.base.PatternCompiler;
                               ^
Note: D:\zoomaio\build\jlinkbase\tmpjars\zoomaio.merged.module\module-info.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

open module zoomaio.main {
    requires java.sql;
    requires static lombok;
    requires javafx.graphics;
    requires javafx.fxml;
    requires javafx.controls;
    requires javafx.web;
    requires org.controlsfx.controls;
    requires jdk.jsobject;
    requires okhttp3;
    requires org.json;
    requires org.jsoup;
    requires jdk.crypto.ec;
    requires selenium.java;
    requires selenium.api;
    requires selenium.chrome.driver;
    requires webdrivermanager;
}

**Comment by siordache** [comment]
So you no longer get this error?
```
Illegal char <:> at index 0: :\zoomaio\build\tmp\expandedArchives\selenium-java-3.141.59.jar_ca554a8fa5a80e39066d65f3fd614f36\META-INF\MANIFEST.MF
```

**Comment by siordache** [comment]
You probably need to add this:
```
jlink {
    ...
    mergedModule {
        ...
        excludeUses("com.google.common.base.PatternCompiler")
    }
}
```

**Comment by nucleate** [comment]
@siordache yeah, now build is fine. Thanks you a lot for help.

**Comment by miguelaferreira** [comment]
I also ran into this issue and this thread was very helpful. Thank you @siordache for the code to fix the selenium jars.

While adding `excludeUses(com.google.common.base.PatternCompiler)` to the merged module config fixed the error in `gradle jlink` build. I now get a runtime error when running the image, and selenium doesn't start the browser anymore.

```java
java.util.ServiceConfigurationError: com.google.common.base.PatternCompiler: module com.functorful.merged.module does not declare `uses`
        at java.base/java.util.ServiceLoader.fail(Unknown Source)
        at java.base/java.util.ServiceLoader.checkCaller(Unknown Source)
        at java.base/java.util.ServiceLoader.<init>(Unknown Source)
        at java.base/java.util.ServiceLoader.load(Unknown Source)
        at com.functorful.merged.module@1.0-SNAPSHOT/com.google.common.base.Platform.loadPatternCompiler(Unknown Source)
        at com.functorful.merged.module@1.0-SNAPSHOT/com.google.common.base.Platform.<clinit>(Unknown Source)
        at com.functorful.merged.module@1.0-SNAPSHOT/com.google.common.base.Strings.isNullOrEmpty(Unknown Source)
        at com.functorful.merged.module@1.0-SNAPSHOT/org.openqa.selenium.remote.internal.OkHttpClient$Factory$1.createClient(Unknown Source)
        at com.functorful.merged.module@1.0-SNAPSHOT/org.openqa.selenium.remote.http.HttpClient$Factory.createClient(Unknown Source)
        at com.functorful.merged.module@1.0-SNAPSHOT/org.openqa.selenium.remote.HttpCommandExecutor.<init>(Unknown Source)
        at com.functorful.merged.module@1.0-SNAPSHOT/org.openqa.selenium.remote.HttpCommandExecutor.<init>(Unknown Source)
        at com.functorful.merged.module@1.0-SNAPSHOT/org.openqa.selenium.remote.service.DriverCommandExecutor.<init>(Unknown Source)
        at com.functorful.merged.module@1.0-SNAPSHOT/org.openqa.selenium.firefox.FirefoxDriver$FirefoxDriverCommandExecutor.<init>(Unknown Source)
        at com.functorful.merged.module@1.0-SNAPSHOT/org.openqa.selenium.firefox.FirefoxDriver.toExecutor(Unknown Source)
        at com.functorful.merged.module@1.0-SNAPSHOT/org.openqa.selenium.firefox.FirefoxDriver.<init>(Unknown Source)
        at appmodule@1.0-SNAPSHOT/com.functorful.app.WebLoader.<init>(Unknown Source)
        at appmodule@1.0-SNAPSHOT/com.functorful.app.SiteLoader.load(Unknown Source)
        at appmodule@1.0-SNAPSHOT/com.functorful.app.SiteTabController$SiteWorkerTask.call(Unknown Source)
        at appmodule@1.0-SNAPSHOT/com.functorful.app.SiteTabController$SiteWorkerTask.call(Unknown Source)
        at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

Does anyone have ideas on how to fix this?

**Comment by siordache** [comment]
It seems that versions of guava >= 26.0 [no longer use a ServiceLoader](https://github.com/google/guava/commit/8287cdfa317ea97a7a5e8e1a0f5a786ae09d2eac#diff-c5ac7ff60eb2b4fc5156dd25cc9f448b007ac487783b1b22e8cc6a77067f323eL80-L93) to create a PatternCompiler.

You can try to configure your build to use such a newer guava version:

```
implementation 'com.google.guava:guava:26.0-jre'
implementation('org.seleniumhq.selenium:selenium-remote-driver:3.141.59') {
    exclude module: 'guava'
}
```

If this works, you no longer need the line `excludeUses(com.google.common.base.PatternCompiler)`.

**Comment by miguelaferreira** [comment]
Thanks for that @siordache, excluding the transitive dependency and adding the upgraded version works perfectly!

**Comment by xdsswar** [comment]
I just edited both jars files, removed the "9" file (not the folder) from slenium and edited the PatternCompiler to be public using Recaf
