### ISSUE TITLE
IllegalAccessError: class cannot access other class becaouse module does not read other module

### ISSUE THREAD

**Issue by matthjes** [beryx/badass-jlink-plugin#127]
Hi,

I'm using kotlin-logging (https://github.com/MicroUtils/kotlin-logging) with slf4j and logback. When I start my application within the IDE everything works, however, after packaging and running I get the following error message:
```
java.lang.IllegalAccessError: class mu.KotlinLogging (in module com.bmw.swhrl.merged.module) cannot access class org.slf4j.LoggerFactory (in module org.slf4j) because module com.bmw.swhrl.merged.module does not read module org.slf4j
	at com.bmw.swhrl.merged.module/mu.KotlinLogging.logger(KotlinLogging.kt:30)
	at swhrldm/com.bmw.swhrl.dm.service.UniqueInstanceEnforcerKt.<clinit>(UniqueInstanceEnforcer.kt:17)
	at swhrldm/com.bmw.swhrl.dm.service.UniqueInstanceEnforcer$run$1.invoke(UniqueInstanceEnforcer.kt:49)
	at swhrldm/com.bmw.swhrl.dm.service.UniqueInstanceEnforcer$run$1.invoke(UniqueInstanceEnforcer.kt:19)
	at com.bmw.swhrl.merged.module/tornadofx.FXTask.call(Async.kt:457)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

I have no idea what this means and how I can fix it. My current module-info.java looks like this:

```
module swhrldm {
    requires kotlin.stdlib;
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.graphics;
    requires tornadofx;
    requires kotlin.logging;
    requires org.slf4j;
    requires ch.qos.logback.classic;
    requires ch.qos.logback.core;
    requires kotlinx.coroutines.core;
    requires kotlinx.coroutines.javafx;

    opens com.bmw.swhrl.dm.ui.view to tornadofx;
    opens com.bmw.swhrl.dm.ui.stylesheet to tornadofx;

    exports com.bmw.swhrl.dm;
}
```

**Comment by matthjes** [comment]
Ok, after I added this:
```
    mergedModule {
        additive = true
        requires("org.slf4j")
    }
```
it's working.

Also had to add `java.naming` to my `module-info.java` as a dependency.
