### ISSUE TITLE
bare spring(without spring boot) project error

### ISSUE THREAD

**Issue by hosseinmp76** [beryx/badass-jlink-plugin#134]
I wanted to make my project using all new frameworks: java14, javafx14, hibernate6-alpha and spring but without using spring boot.
I can run the jlink task successfully but when I try to run the image I get this error:
```
Caused by: org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://www.springframework.org/schema/context]
Offending resource: file [/home/hosseinmp76/Documents/eclipse-workspace/WorkFlowPlanner/build/image/hello-linux/bin/src/main/resources/ir/hosseinmp76/workFlowPlanner/utills/applicationContext.xml]
```
I used almost every different setting for build.gradle but I was unable to solve this problem.
my project can be found at: [https://github.com/hosseinmp76/work-flow-planner](https://github.com/hosseinmp76/work-flow-planner)
jlink setting in build.gradle:
```
jlink {
  options = [
	'--strip-debug',
	'--compress',
	'2',
	'--no-header-files',
	'--no-man-pages'
  ]

	targetPlatform("linux") {
        jdkHome = "/usr/lib/jvm/jdk-14"
    }

    targetPlatform("win") {
        jdkHome = "/usr/lib/jvm/jdk-14-win"
    }
  launcher{
	name = 'hello'
	jvmArgs = [
	  '-Dlog4j.debug=true', '-Dlog4j.configurationFile={{BIN_DIR}}/log4j2.xml'
	]
  }
  addExtraDependencies("javafx")


//  forceMerge 'istack', 'stax','jackson', 'log4j-api', 'log4j-core', 'spring-contex', 'jaxb-api', 'byte-buddy', 'classgraph'
	forceMerge 'jackson', 'jaxb-api', 'activation', 'istack', 'stax', 'log4j-api'

mergedModule {
    additive = true
//    uses 'javax.validation.valueextraction.ValueExtractor'
//    uses 'javax.validation.ConstraintValidator'
	excludeRequires 'com.fasterxml.jackson.module.paramnames'
	excludeProvides implementation: 'com.sun.xml.bind.v2.ContextFactory'
    excludeProvides servicePattern: 'javax.enterprise.inject.*'
    excludeProvides service: 'org.apache.logging.log4j.spi.Provider'      
	}
	jpackage {
		imageName = 'HelloFX'
		skipInstaller = true
		targetPlatformName = "linux"
		installerName = 'HelloFX'
		installerType = 'deb'
		targetPlatformName = "linux"
      }

}

tasks.jlink.doLast {
    copy {
        from('src/main/resources')
        into("$buildDir/image/hello-linux/bin")
    }
    
    copy {
        from('src/main/resources')
        into("$buildDir/image/hello-linux/bin/src/main/resources")
    }
    // Spring performs its magic by scanning the classpath, but in a modular application the classpath is replaced by the module-path.
    // To circumvent this problem, we copy all resources into the 'config' directory and set this directory as classpath.
    copy {
        from "src/main/resources"
        into "$imageDir.asFile/hello-linux/bin/config"
    }

    // Spring also needs to read the .class files, therefore they should be accessible via classpath.
    // Note: These .class files are only used as resources, they will not be loaded by a classloader.
    copy {
        from "$buildDir/classes/java/main/ir/hosseinmp79/workFlowPlanner"
        into "$imageDir.asFile/hello-linux/bin/config/ir/hosseinmp79/workFlowPlanner/for-spring-classpath-scanner"
    }
}

configurations {
   springFactoriesHolder { transitive = false }
}

prepareMergedJarsDir.doLast {
    // extract and merge META-INF/spring.factories from springFactoriesHolder
    def factories = configurations.springFactoriesHolder.files.collect {
        def props = new Properties()
        props.load(zipTree(it).matching { include 'META-INF/spring.factories' }.singleFile.newInputStream())
        props
    }
    def mergedProps = new Properties()
    factories.each { props ->
        props.each { key, value ->
            def oldVal = mergedProps[key]
            mergedProps[key] = oldVal ? "$oldVal,$value" : value
        }
    }
    def content = mergedProps.collect { key, value ->
        def v = (value as String).replace(',', ',\\\n')
        "$key=$v"
    }.join('\n\n')
    mkdir("$jlinkBasePath/META-INF")
    new File("$jlinkBasePath/META-INF/spring.factories").text = content

    // insert META-INF/spring.factories into the main jar
    ant.zip(update: "true", destfile: jar.archivePath, keepcompression: true) {
        fileset(dir: "$jlinkBasePath", includes: 'META-INF/**')
    }
}
```
one of my problem is how to copy resources to the image. I had to copy them twice in
`$buildDir/image/hello-linux/bin/`
and in
`$buildDir/image/hello-linux/bin/src/main/resources`
so when I run the gradle run task I can get the spring application context with:
```
new FileSystemXmlApplicationContext ("src/main/resources/ir/hosseinmp76/workFlowPlanner/utills/applicationContext.xml");
```
I'm stuck almost two week for making an Image. thanks in advance for helping

**Comment by siordache** [comment]
@hosseinmp76 I submitted a [pull request](https://github.com/hosseinmp76/work-flow-planner/pull/1) with the necessary changes.

**Comment by hosseinmp76** [comment]
> @hosseinmp76 I submitted a [pull request](https://github.com/hosseinmp76/work-flow-planner/pull/1) with the necessary changes.

Thank you for your help. but I still get the same error but with different stacktrace:
```
Caused by: org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://www.springframework.org/schema/context]
Offending resource: file [/home/hosseinmp76/Documents/eclipse-workspace/WorkFlowPlanner/src/main/resources/ir/hosseinmp76/workFlowPlanner/utills/applicationContext.xml]

        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.parsing.FailFastProblemReporter.error(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.parsing.ReaderContext.error(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.parsing.ReaderContext.error(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.error(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.context.support.AbstractApplicationContext.refresh(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.context.support.FileSystemXmlApplicationContext.<init>(Unknown Source)
        at WorkFlowPlanner.merged.module/org.springframework.context.support.FileSystemXmlApplicationContext.<init>(Unknown Source)
        at ir.hosseinmp76.workFlowPlanner/ir.hosseinmp76.workFlowPlanner.utills.UIUtills.getContext(Unknown Source)
        at ir.hosseinmp76.workFlowPlanner/ir.hosseinmp76.workFlowPlanner.ui.FXApp.main(Unknown Source)
        ... 11 more
Exception running application ir.hosseinmp76.workFlowPlanner.ui.FXApp
```

**Comment by siordache** [comment]
I cannot reproduce this error. However, the way you initialize your ApplicationContext is questionable. Using paths such as:
```
final static String str = "src/main/resources/ir/hosseinmp76/workFlowPlanner/utills/applicationContext.xml";
```
is error prone.

**Comment by hosseinmp76** [comment]
> I cannot reproduce this error. However, the way you initialize your ApplicationContext is questionable. Using paths such as:
> 
> ```
> final static String str = "src/main/resources/ir/hosseinmp76/workFlowPlanner/utills/applicationContext.xml";
> ```
> 
> is error prone.

Can I ask what is your OS?

As I know there is two way to get the context: using ClassPathXmlApplicationContext and FileSystemXmlApplicationContext. I tested both but I was unable to use class path location without `src/main/resources`. Am I missing something?

**Comment by siordache** [comment]
I submitted [another pull request](https://github.com/hosseinmp76/work-flow-planner/pull/2) that replaces FileSystemXmlApplicationContext with ClassPathXmlApplicationContext.

Both `./gradlew run` and the runtime-image work fine on my Ubuntu platform.

**Comment by siordache** [comment]
The `Cannot derive uses clause from service loader invocation` messages tell you that the plugin could not detect all services referenced in your applcation's dependencies. This means that your application may crash complaining about some services. If this is the case, you need to add the  `uses` clauses for the problematic services to the `mergedModule` block.

**Comment by hosseinmp76** [comment]
> I submitted [another pull request](https://github.com/hosseinmp76/work-flow-planner/pull/2) that replaces FileSystemXmlApplicationContext with ClassPathXmlApplicationContext.
> 
> Both `./gradlew run` and the runtime-image work fine on my Ubuntu platform.

Thanks for your great help.
run task works good but I get the same error this time not able to read from classpath:
```
Caused by: org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://www.springframework.org/schema/context]
Offending resource: class path resource [ir/hosseinmp76/workFlowPlanner/utills/applicationContext.xml]
```
does the app graphical window start when you excute the image? if yes I think the problem is with my computer I mean jdk or something similar.

**Comment by siordache** [comment]
That's what I see when executing the image:

![image](https://user-images.githubusercontent.com/1158863/80085061-07a39a00-8558-11ea-914b-3d900254a5ad.png)

**Comment by hosseinmp76** [comment]
> That's what I see when executing the image:
> 
> ![image](https://user-images.githubusercontent.com/1158863/80085061-07a39a00-8558-11ea-914b-3d900254a5ad.png)

Thank you for your great help. the problem is very strange.
Anyway thank you for your great plugin and your helps around it.

**Comment by hosseinmp76** [comment]
I think I should close this issue then. cause it is not reproducible for others.
