### ISSUE TITLE
StackOverflowException when running jlink

### ISSUE THREAD

**Issue by cbeust** [beryx/badass-jlink-plugin#158]
Getting a `StackOverflowException` when running `jlink`.

Plug-in:

```
id("org.beryx.jlink") version "2.22.1"
```

Java: 
```
java version "14.0.1" 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
```

```
* What went wrong:
Execution failed for task ':prepareMergedJarsDir'.
> java.lang.StackOverflowError (no error message)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':prepareMergedJarsDir'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:207)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:186)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:356)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.StackOverflowError
        at org.beryx.jlink.util.Util.getArtifacts(Util.groovy:250)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.doCall(DependencyManager.groovy:162)
        at org.beryx.jlink.util.DependencyManager$_collectAllDescendants_closure14.call(DependencyManager.groovy)
        at org.beryx.jlink.util.DependencyManager.collectAllDescendants(DependencyManager.groovy:159)
        at org.beryx.jlink.util.DependencyManager.access$2(DependencyManager.groovy)
```

**Comment by siordache** [comment]
Can you post your build.gradle?

**Comment by siordache** [comment]
In 2.22.2 I made a change to prevent the StackOverflowException. However, I'm not 100% sure that this fix solves the problem, because I cannot reproduce the issue.

Please give it a try.

**Comment by cbeust** [comment]
```
@file:Suppress("MayBeConstant")

fun DependencyHandler.impl(vararg dep: Any) = dep.forEach { implementation(it) }
fun DependencyHandler.testImpl(vararg dep: Any) = dep.forEach { testImplementation(it) }

plugins {
    java
    id("org.jetbrains.kotlin.jvm") version "1.3.72"
    application
    id("edu.sc.seis.launch4j") version "2.4.8"
    id("org.beryx.jlink") version "2.22.1"
}

configurations.all {
    resolutionStrategy {
        dependencySubstitution {
            // The maven property ${osgi.platform} is not handled by Gradle
            // so we replace the dependency, using the osgi platform from the project settings
            val os = System.getProperty("os.name").toLowerCase()
            if (os.contains("windows")) {
                substitute(module("org.eclipse.platform:org.eclipse.swt.\${osgi.platform}")).with(
                        module("org.eclipse.platform:org.eclipse.swt.win32.win32.x86_64:3.115.0"))
            }
            else if (os.contains("linux")) {
                substitute(module("org.eclipse.platform:org.eclipse.swt.\${osgi.platform}")).with(
                        module("org.eclipse.platform:org.eclipse.swt.gtk.linux.x86_64:3.115.0"))
            }
            else if (os.contains("mac")) {
                substitute(module("org.eclipse.platform:org.eclipse.swt.\${osgi.platform}")).with(
                        module("org.eclipse.platform:org.eclipse.swt.cocoa.macosx.x86_64:3.115.0"))
            }
        }
    }
}

repositories {
    jcenter()
    mavenCentral()
    maven { setUrl("https://plugins.gradle.org/m2") }
}

defaultTasks(ApplicationPlugin.TASK_RUN_NAME)

object This {
    val artifactId = "sixty"
}

dependencies {
    impl(kotlin("stdlib"), "com.beust:jcommander:1.72", "ch.qos.logback:logback-classic:1.2.3",
            "org.eclipse.platform:org.eclipse.jface:3.21.0",
            "org.eclipse.platform:org.eclipse.jface.text:3.16.400")
    testImpl(kotlin("test"), "org.testng:testng:7.0.0", "org.assertj:assertj-core:3.10.0")
}

application {
    mainClassName = "com.beust.app.MainKt"
    if (System.getProperty("os.name").toLowerCase().contains("mac")) {
        applicationDefaultJvmArgs = listOf("-XstartOnFirstThread")
    }
}

tasks {
    withType<Test> {
        useTestNG()
    }
}


jlink {
    options.set(listOf("--strip-debug", "--compress", "2", "--no-header-files", "--no-man-pages"))
    launcher{
        name = "hello"
        jvmArgs = listOf("-Dlog4j.configurationFile=./log4j2.xml")
    }
}
```

**Comment by siordache** [comment]
Thanks! I was able to reproduce the StackOverflowException and checked that it no longer occurs when using org.beryx.jlink 2.22.2.

However, I suspect that you didn't configure a module-info.java for your application, so your build will still fail. If you don't want to modularize your application, then you should use the [org.beryx.runtime plugin](https://github.com/beryx/badass-runtime-plugin) instead of this one.
