### ISSUE TITLE
Enhancement: Infer module path

### ISSUE THREAD

**Issue by oliver-brm** [beryx/badass-jlink-plugin#198]
In my application, I'm using service modules and separate modules which provide those services. Gradle 7.2 itself is able to infer the module path for the application by looking at the dependencies - service implementations show up as `runtime project(...)` dependencies. **Example:**

```groovy
dependencies {
    implementation project(':greeting-service')        // this is the service API
    runtimeOnly project(':greeting-provider-fixed')  // this is the service implementation
}
```

I'm using the `badass-jlink-plugin:2.24.2`, which however does not infer the module path for those service implementations. It's working fine if I specify the module path in a `customImage` declaration. **Example:**

```groovy
jlink {
    customImage {
        appModules = [
                'org.example.jpms.hello.main',
                'org.example.jpms.hello.greeting.service',
                'org.example.jpms.hello.greeting.provider.fixed']
    }
}
```

This can get a bit cumbersome with more and more modules added to the application. Wouldn't it be possible to derive the module path from the application's dependencies? I would be glad to contribute to that feature.

I have pushed a **reproducer** project here: https://github.com/oliver-brm/jpms-hello.git. To reproduce:

  1. Remove the `customImage` declaration from `build.gradle` 
  2. Run the `jlink` or `jpackage` task
  3. Try to execute `build/image/bin/greeting`, it will print:
```
Exception in thread "main" java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at org.example.jpms.hello.main/org.example.jpms.hello.App.main(Unknown Source)
```

**Comment by oliver-brm** [comment]
OK, cool! I would look if I can somehow extract the module path which the `java` plugin creates. That would make life a bit easier and it's more predictable for the user what the module path will be. I've never created a plugin for Gradle, nor modified one. So, I'm very happy for any hint how I might start this one.
