### ISSUE TITLE
Runtime exception with Apache HTTP client

### ISSUE THREAD

**Issue by batraz90** [beryx/badass-jlink-plugin#21]
I've written a small JavaFX application which depends on a library that makes use of the Apache HTTP client and Jackson. It runs fine when using Gradle run but throws an exception when running on a modular runtime created with badass-jlink:

```
com.fasterxml.jackson.databind.ext.Java7Support <clinit>
WARNING: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
        at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
        at javafx.graphics/javafx.scene.Node.fireEvent(Unknown Source)
        at javafx.controls/javafx.scene.control.Button.fire(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
        at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
        at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Unknown Source)
        at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1200(Unknown Source)
        at javafx.graphics/javafx.scene.Scene.processMouseEvent(Unknown Source)
        at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.View.notifyMouse(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
        at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
        ... 48 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
        at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
        at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at com.fxtestapp.merged.module/org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(Unknown Source)
        at com.fxtestapp.merged.module/org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(Unknown Source)
        at com.fxtestapp.merged.module/org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(Unknown Source)
        at com.fxtestapp.merged.module/org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(Unknown Source)
        at com.fxtestapp.merged.module/org.apache.http.impl.execchain.MainClientExec.establishRoute(Unknown Source)
        at com.fxtestapp.merged.module/org.apache.http.impl.execchain.MainClientExec.execute(Unknown Source)
        at com.fxtestapp.merged.module/org.apache.http.impl.execchain.ProtocolExec.execute(Unknown Source)
        at com.fxtestapp.merged.module/org.apache.http.impl.execchain.RetryExec.execute(Unknown Source)
        at com.fxtestapp.merged.module/org.apache.http.impl.execchain.RedirectExec.execute(Unknown Source)
        at com.fxtestapp.merged.module/org.apache.http.impl.client.InternalHttpClient.doExecute(Unknown Source)
        at com.fxtestapp.merged.module/org.apache.http.impl.client.CloseableHttpClient.execute(Unknown Source)
        at com.fxtestapp.merged.module/org.apache.http.impl.client.CloseableHttpClient.execute(Unknown Source)
        at com.fxtestapp.merged.module/org.apache.http.impl.client.CloseableHttpClient.execute(Unknown Source)
        at com.fxtestapp.merged.module/com.wavesplatform.wavesj.Node.exec(Unknown Source)
        at com.fxtestapp.merged.module/com.wavesplatform.wavesj.Node.send(Unknown Source)
        at com.fxtestapp.merged.module/com.wavesplatform.wavesj.Node.getHeight(Unknown Source)
        at com.fxtestapp/com.fxtestapp.FXMLController.handleButtonAction(Unknown Source)
        ... 58 more
```

here's my build.gradle
```
plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.5'
    id 'java'
    id 'org.beryx.jlink' version '2.3.1'
}

repositories {
    mavenCentral()
}

sourceCompatibility = 11
targetCompatibility = 11

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile group: 'com.wavesplatform', name: 'wavesj', version: '0.13.1'
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.9.8'
}

javafx {
    modules = ['javafx.controls',
               'javafx.fxml'
    ]
}

mainClassName = "$moduleName/com.fxtestapp.MainApp"

group 'com.fxtestapp'
version '1.0-SNAPSHOT'

jlink {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    launcher{
        name = 'MainApp'
    }
    forceMerge('wavesj')
    mergedModule {
        requires 'java.naming';
        requires 'java.logging';
        requires 'java.sql';
        requires 'java.xml';
        requires 'java.security.jgss';
        provides 'com.fasterxml.jackson.core.JsonFactory' with 'com.fasterxml.jackson.core.JsonFactory';
        provides 'com.fasterxml.jackson.core.ObjectCodec' with 'com.fasterxml.jackson.databind.ObjectMapper';
    }
}
```

module-info.java:
```
module com.fxtestapp {
    requires javafx.controls;
    requires javafx.fxml;
    requires com.fasterxml.jackson.core;
    requires wavesj;

    opens com.fxtestapp to javafx.fxml;
    exports com.fxtestapp;
}
```
the JavaFX application:
```
package com.fxtestapp;
import com.wavesplatform.wavesj.Node;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
public class MainApp extends Application {
    @Override
    public void start(Stage stage) throws Exception {
        Parent root = FXMLLoader.load(getClass().getResource("/fxml/Scene.fxml"));
        Scene scene = new Scene(root);
        var node = new Node();
        stage.setTitle(String.valueOf(node.getHeight()));
        stage.setScene(scene);
        stage.show();
    }
    public static void main(String[] args) {
        launch(args);
    }
}

```

I've also tried adding Jackson and the Apache HTTP client as a dep seperately but that did not work either.

**Comment by batraz90** [comment]
That'll do. Thanks!

**Comment by batraz90** [comment]
I just tried using the same project in Kotlin/TornadoFX. Gives me the same error despite of using the runtime instead of jlink plugin. Any idea what causes this?

**Comment by siordache** [comment]
Using the [workaround suggested here](https://bugs.openjdk.java.net/browse/JDK-8211426?focusedCommentId=14218233&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14218233), I changed your original build.gradle (the one using `org.beryx.jlink`) as shown below:

```
jlink {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    launcher{
        name = 'MainApp'
        jvmArgs = ['-Djdk.tls.client.protocols=TLSv1.2']
    }
    ...
}
```

With this adjustment the application started without errors. I hope this workaround also works for your Kotlin/TornadoFX project.

**Comment by batraz90** [comment]
Adding '-Djdk.tls.client.protocols=TLSv1.2' to jvmArgs works indeed but only for Java projects. 

I've tried creating a similar application with Kotlin and I couldn't make it work. **When using the runtime plugin**, the application works with 'gradle run' but doesn't work when using the image:
```
Mar 16, 2019 4:41:28 PM tornadofx.DefaultErrorHandler uncaughtException
SEVERE: Uncaught error
java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: javax/naming/NamingException
        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:944)
        at com.wavesplatform.wavesj.Node.createDefaultClient(Node.java:106)
        at com.wavesplatform.wavesj.Node.<init>(Node.java:62)
        at org.beryx.runtime.test.kotlin.HelloWorld$root$1.invoke(HelloWorld.kt:21)
        at org.beryx.runtime.test.kotlin.HelloWorld$root$1.invoke(HelloWorld.kt:19)
        at tornadofx.LayoutsKt.hbox(Layouts.kt:384)
        at tornadofx.LayoutsKt.hbox$default(Layouts.kt:96)
        at org.beryx.runtime.test.kotlin.HelloWorld.<init>(HelloWorld.kt:20)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.base/java.lang.Class.newInstance(Unknown Source)
        at tornadofx.FXKt.find(FX.kt:410)
        at tornadofx.FXKt.find$default(FX.kt:399)
        at tornadofx.App.start(App.kt:78)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: javax.naming.NamingException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 25 more
```
Building the image with badass-jlink did not work in the first place.

https://github.com/batraz90/badass-runtime-tornadofx
https://github.com/batraz90/badass-jlink-tornadofx
