### ISSUE TITLE
jlink image and spring boot

### ISSUE THREAD

**Issue by Whya5448** [beryx/badass-jlink-plugin#30]
sorry for amatur english

when i excute jlink task for using spring-boot project 
task are success but i can't run image cuz (merged.module) does not read (original.module)
==> think Spring-Boot want to read original.module not a merged. how can i change it?
so i try modify mergedModule {} but i can't solved. (maybe my skills not enough.)

**errors**

	  .   ____          _            __ _ _
	 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
	( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
	 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
	  '  |____| .__|_| |_|_| |_\__, | / / / /
	 =========|_|==============|___/=/_/_/_/
	 :: Spring Boot ::

	[INFO ] LOG: Starting ClientApplication.Companion on DESKTOP-15TQOHF with PID 8240 (started by Whya5 in C:\Users\Whya5\IdeaProjects\zariel\client\build\dc-eso-client\bin)
	[INFO ] LOG: No active profile set, falling back to default profiles: default
	[ERROR] LOG: Application run failed
	java.lang.IllegalStateException: Cannot load configuration class: org.metalscraps.eso.lang.client.ClientApplication
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.context.support.AbstractApplicationContext.refresh(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.boot.SpringApplication.refresh(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.boot.SpringApplication.refreshContext(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.boot.SpringApplication.run(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.boot.SpringApplication.run(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.boot.SpringApplication.run(Unknown Source)
			at org.metalscraps.eso.lang.client/org.metalscraps.eso.lang.client.ClientApplication$Companion.main(Unknown Source)
			at org.metalscraps.eso.lang.client/org.metalscraps.eso.lang.client.ClientApplication.main(Unknown Source)
	Caused by: org.springframework.cglib.core.CodeGenerationException: java.lang.IllegalAccessException-->module org.metalscraps.eso.lang.client.merged.module does not read module org.metalscraps.eso.lang.client
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.cglib.core.ReflectUtils.defineClass(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.cglib.core.AbstractClassGenerator.generate(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.cglib.proxy.Enhancer.generate(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.cglib.core.internal.LoadingCache$2.call(Unknown Source)
			at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.cglib.core.internal.LoadingCache.createEntry(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.cglib.core.internal.LoadingCache.get(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.cglib.core.AbstractClassGenerator.create(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.cglib.proxy.Enhancer.createHelper(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.cglib.proxy.Enhancer.createClass(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.context.annotation.ConfigurationClassEnhancer.createClass(Unknown Source)
			at org.metalscraps.eso.lang.client.merged.module/org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(Unknown Source)
			... 13 common frames omitted
	Caused by: java.lang.IllegalAccessException: module org.metalscraps.eso.lang.client.merged.module does not read module org.metalscraps.eso.lang.client
			at java.base/java.lang.invoke.MethodHandles.privateLookupIn(Unknown Source)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
			at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
			at java.base/java.lang.reflect.Method.invoke(Unknown Source)
			... 28 common frames omitted

my main-module build.gradle and this sub-module build.gradle
**main**

    allprojects {
        apply plugin: 'java'
        group group
        version '1.0'
        sourceCompatibility = 11
        targetCompatibility = 11
        compileJava.options.encoding = "utf-8"
        compileTestJava.options.encoding = "utf-8"
    
        repositories {
            jcenter()
            mavenCentral()
        }
    
    }
    
    subprojects {
        ext {
            badass = '2.6.5'
            javaModule = '1.4.1'
            jackson = "2.9.8"
            commonsio = "2.6"
            group = "org.metalscraps.eso.lang"
        }
    
        dependencies {
            compileOnly 'org.projectlombok:lombok:1.18.6'
            annotationProcessor 'org.projectlombok:lombok:1.18.6'
            testCompileOnly 'junit:junit:4.12'
            runtimeOnly 'ch.qos.logback:logback-classic:1.2.3'
            compileOnly 'org.slf4j:slf4j-api:1.7.25'
            implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
        }
    }

**sub**

    plugins {
        id 'org.beryx.jlink' version '2.6.5'
        id "org.javamodularity.moduleplugin" version "1.4.1"
        id 'org.jetbrains.kotlin.jvm' version "1.3.21"
        id 'org.jetbrains.kotlin.plugin.spring' version '1.3.21'
        id 'org.springframework.boot' version '2.1.3.RELEASE'
    }
    apply plugin: 'io.spring.dependency-management'
    dependencies {
        configurations.all {
            exclude group: "commons-logging", module: "commons-logging"
            exclude group: "com.google.code.findbugs", module: "jsr305"
        }
    
        implementation project(':library')
        implementation "com.fasterxml.jackson.core:jackson-databind:${jackson}"
        implementation "com.fasterxml.jackson.module:jackson-module-kotlin:${jackson}"
        implementation 'org.jetbrains.kotlin:kotlin-reflect'
        implementation 'org.springframework.boot:spring-boot-starter:2.1.3.RELEASE'
    }
    
    def sImageName = 'dc-eso-client'
    def sModuleName = 'org.metalscraps.eso.lang.client'
    def sMainClass = 'org.metalscraps.eso.lang.client.ClientApplication'
    mainClassName = "${sModuleName}/${sMainClass}"
    springBoot { mainClassName = sMainClass }
    jar {
        manifest { attributes 'Implementation-Title': sModuleName, 'Main-Class': sMainClass }
        enabled = true
    }
    jlink {
        moduleName = sModuleName
        mergedModuleName = "${sModuleName}.merged.module"
        imageName = sImageName
        options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
        imageZip = file("$buildDir/${sImageName}-${version}.zip")
        launcher {
            name = 'launch'
            jvmArgs = ['-Dlogback.configurationFile=./logback.xml',
                       "--add-opens java.base/java.lang=${sModuleName}.merged.module",
                       "--add-opens java.base/java.io=${sModuleName}.merged.module",
            ]
        }
    
        mergedModule {
            requires 'java.management'
            requires 'java.naming'
            requires 'java.logging'
            requires 'jdk.httpserver'
            requires 'java.scripting'
            requires 'java.sql'
            requires 'java.prefs'
            requires 'java.rmi'
            requires 'java.xml'
            requires 'java.desktop'
            requires 'java.instrument'
            requires 'jdk.unsupported'
    
            uses 'kotlin.reflect.jvm.internal.impl.util.ModuleVisibilityHelper'
            uses 'kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader'
            uses 'kotlin.reflect.jvm.internal.impl.resolve.ExternalOverridabilityCondition'
            uses 'java.nio.file.spi.FileSystemProvider'
    
            provides 'com.fasterxml.jackson.core.JsonFactory' with 'com.fasterxml.jackson.core.JsonFactory'
            provides 'org.apache.commons.logging.LogFactory' with 'org.apache.commons.logging.LogFactoryService'
            provides 'kotlin.reflect.jvm.internal.impl.resolve.ExternalOverridabilityCondition' with 'kotlin.reflect.jvm.internal.impl.load.java.ErasedOverridabilityCondition',
                    'kotlin.reflect.jvm.internal.impl.load.java.FieldOverridabilityCondition',
                    'kotlin.reflect.jvm.internal.impl.load.java.JavaIncompatibilityRulesOverridabilityCondition'
            provides 'kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader' with 'kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl'
            provides 'com.fasterxml.jackson.databind.Module' with 'com.fasterxml.jackson.module.kotlin.KotlinModule'
            provides 'com.fasterxml.jackson.core.ObjectCodec' with 'com.fasterxml.jackson.databind.ObjectMapper'
        }
    
    }
    
    tasks.jlink.doLast {
        copy {
            from('src/main/resources')
            into("$buildDir/${sImageName}/bin")
        }
    }
    compileKotlin {
        kotlinOptions {
            jvmTarget = "1.8"
        }
    }
    compileTestKotlin {
        kotlinOptions {
            jvmTarget = "1.8"
        }
    }

and my github repo
https://github.com/Whya5448/zariel/tree/KOTLIN

i'm using 

gradle 5.2.1, 

openjdk 11.0.2 2019-01-15 LTS
OpenJDK Runtime Environment Zulu11.29+3-CA (build 11.0.2+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.29+3-CA (build 11.0.2+7-LTS, mixed mode)

thanks.

**Comment by siordache** [comment]
I cloned your repo, but there is no reference to spring in your code. Also, the `ClientApplication` class is missing. There is only a `ClientMain` class, which launches a steam game.
Please update your repo, so I can analyze this issue.

**Comment by Whya5448** [comment]
My source in breach named “KOTLIN”

2019년 2월 28일 (목) 19:06, Serban Iordache <notifications@github.com>님이 작성:

**Comment by the-other-one** [comment]
You're right. I was on the master branch.

**Comment by siordache** [comment]
And I posted from the wrong account. 😃

**Comment by siordache** [comment]
I submitted the necessary changes as a [pull request](https://github.com/Whya5448/zariel/pull/8).

**Comment by Whya5448** [comment]
thanks for your help.

--add-reads <== i didn't know about it. sorry :(
(and i don't even now why need to copy kotlin classes, but try to learn.)

thanks again.

**Comment by siordache** [comment]
Spring retrieves bean definitions and annotations (such as `@Autowired`) by scanning the classpath. Therefore, some Spring classes (such as [ClassPathBeanDefinitionScanner](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/ClassPathBeanDefinitionScanner.html) or [EntityScanner](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/domain/EntityScanner.html)) expect to find the application classes on the classpath. But in a modular application all classes are on the module-path. That's why we still need to confgure the `-cp` jvm argument and to copy the application classes to the specified directory. Yes, it's an ugly workaround.
