### ISSUE TITLE
JAXB incompatibility

### ISSUE THREAD

**Issue by mwkroening** [beryx/badass-jlink-plugin#38]
I'm struggling to get [JAXB-RI](https://eclipse-ee4j.github.io/jaxb-ri/) working in the jlink image.

To help troubleshooting I created a simple example project: [mwkroening/badass-jlink-jaxb](https://github.com/mwkroening/badass-jlink-jaxb)

Running the app directly via `./gradlew run` or running the distribution built by `./gradlew assemble` gives the expected output:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<app>
    <greeting>Hello World.</greeting>
</app>
```

Running the image generated by `./gradlew jlink` gives:
```
Exception in thread "main" javax.xml.bind.DataBindingException: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at java.xml.bind/javax.xml.bind.JAXB._marshal(JAXB.java:559)
	at java.xml.bind/javax.xml.bind.JAXB.marshal(JAXB.java:417)
	at io.github.mwkroening.badassjlinkjaxb/io.github.mwkroening.badassjlinkjaxb.App.main(App.java:9)
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at java.xml.bind/javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:232)
	at java.xml.bind/javax.xml.bind.ContextFinder.find(ContextFinder.java:375)
	at java.xml.bind/javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
	at java.xml.bind/javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
	at java.xml.bind/javax.xml.bind.JAXB$Cache.<init>(JAXB.java:97)
	at java.xml.bind/javax.xml.bind.JAXB.getContext(JAXB.java:124)
	at java.xml.bind/javax.xml.bind.JAXB._marshal(JAXB.java:548)
	... 2 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.xml.bind/javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:92)
	at java.xml.bind/javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:125)
	at java.xml.bind/javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:230)
	... 8 more
```

Can this issue be fixed with the Badass JLink Plugin or is it an incompatibility of [eclipse-ee4j/jaxb-api](https://github.com/eclipse-ee4j/jaxb-api) or [eclipse-ee4j/jaxb-ri](https://github.com/eclipse-ee4j/jaxb-ri) with jlink?

**Comment by lenborje** [comment]
I believe there is something fishy with the eclipse-ee4j. I have also not been able to get it to work, yet I can use the slightly older Eclipse MOxy JAXB implementation, as well as the original JAXB-RI.

Replacing your dependency block with
```
dependencies {
    implementation("javax.xml.bind:jaxb-api:2.+")
    runtimeOnly("com.sun.xml.bind:jaxb-ri:2.+")
}
```
makes it work.

**Comment by siordache** [comment]
jlink doesn’t automatically resolve modules that contain service providers.,You need to provide the `--bind-service` option explicitely:

```
jlink {
    addOptions("--bind-services")
}
```
