### ISSUE TITLE
`UnsupportedCharsetException: Cp65001` on Windows

### ISSUE THREAD

**Issue by najiji** [beryx/badass-jlink-plugin#49]
I'm trying to link my project using jlink on Windows, but get this charset exception. I tried changing the terminal to UTF-8 by `chcp 65001` which did not resolve the issue. Also passing 
`-Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8` in `gradle.properties` did not resolve the issue. 

I am running Windows 10 with OpenJDK 12. The `jlink` task works fine both on Linux and macOS.
The issue is also present in the `badass-jlink-example-log4j2-javafx` example project. 

Steps to reproduce:
- Fresh installation of Windows 10
- Install OpenJDK 12
- Install git
- Clone example repo
- run `.\gradlew jlink`

```
> Task :prepareModulesDir FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':prepareModulesDir'.
> Cp65001

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':prepareModulesDir'.
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:46)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.nio.charset.UnsupportedCharsetException: Cp65001
        at org.beryx.jlink.util.Util.getDefaultModuleName(Util.groovy:77)
        at org.beryx.jlink.data.JlinkPluginExtension$_closure2.doCall(JlinkPluginExtension.groovy:66)
        at org.beryx.jlink.data.JlinkPluginExtension$_closure2.call(JlinkPluginExtension.groovy)
        at org.gradle.api.internal.provider.DefaultProvider.getOrNull(DefaultProvider.java:41)
        at org.gradle.api.internal.provider.AbstractMappingProvider.getOrNull(AbstractMappingProvider.java:54)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.withFinalValue(AbstractMinimalProvider.java:75)
        at org.gradle.api.internal.provider.DefaultPropertyState.makeFinal(DefaultPropertyState.java:123)
        at org.gradle.api.internal.provider.AbstractProperty.beforeRead(AbstractProperty.java:74)
        at org.gradle.api.internal.provider.DefaultPropertyState.isPresent(DefaultPropertyState.java:154)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$DefaultPropertyValue.getValue(AbstractNestedRuntimeBeanNode.java:151)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$DefaultPropertyValue.validate(AbstractNestedRuntimeBeanNode.java:165)
        at org.gradle.api.internal.tasks.DefaultTaskInputPropertySpec.validate(DefaultTaskInputPropertySpec.java:68)
        at org.gradle.api.internal.tasks.execution.DefaultTaskProperties.validate(DefaultTaskProperties.java:197)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:50)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        ... 24 more


* Get more help at https://help.gradle.org

BUILD FAILED in 10s
8 actionable tasks: 6 executed, 2 up-to-date
```

**Comment by siordache** [comment]
I cannot reproduce the problem, but your stacktrace indicates that the error occurs in [this line](https://github.com/beryx/badass-jlink-plugin/blob/a0f1b7d47423bacc3035e876b87d8804bfba898c/src/main/groovy/org/beryx/jlink/util/Util.groovy#L77):
```
def moduleInfoFile = new File(moduleInfoDir, 'module-info.java')
```

Does the path to your project contain non-ASCII characters?

**Comment by najiji** [comment]
I suspected that as well, but my module info file only contains ascii characters (as shown by the `file` command). I also have the same problem with the `badass-jlink-example-log4j2-javafx` project.

The windows 10 installation is pristine and I am using Windows Powershell

**Comment by najiji** [comment]
Update:
I could resolve the issue by setting the environment variable `JAVA_TOOL_OPTIONS`.

CMD:
` SET JAVA_TOOL_OPTIONS="-Dsun.jnu.encoding=UTF8 -Dfile.encoding=UTF8 -Ds=0"`

Powershell:
`$env:JAVA_TOOL_OPTIONS="-Dsun.jnu.encoding=UTF8 -Dfile.encoding=UTF8 -Ds=0"`

This can be closed

**Comment by siordache** [comment]
Great, I'm glad you solved it!
