### ISSUE TITLE
Unable to avoid circular dependency?

### ISSUE THREAD

**Issue by gerco** [beryx/badass-jlink-plugin#52]
I'm not sure whether this is an issue with the plugin or something else, but I hope you can help me figure it out:

I'm using Spring Boot to create a JavaFX application and had to specify the `mergedModule` section in the gradle configuration due to a missing declaration in the autogenerated module-info (`requires transitive 'org.apache.logging.log4j'`). Now I can successfully jlink the image, but it doesn't run. I get this error:

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application init method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Cannot load configuration class: com.mycompany.my.app.Main
	at my.app.merged.module/org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(Unknown Source)
	at my.app.merged.module/org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(Unknown Source)
	at my.app.merged.module/org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(Unknown Source)
	at my.app.merged.module/org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(Unknown Source)
	at my.app.merged.module/org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(Unknown Source)
	at my.app.merged.module/org.springframework.context.support.AbstractApplicationContext.refresh(Unknown Source)
	at my.app.merged.module/org.springframework.boot.SpringApplication.refresh(Unknown Source)
	at my.app.merged.module/org.springframework.boot.SpringApplication.refreshContext(Unknown Source)
	at my.app.merged.module/org.springframework.boot.SpringApplication.run(Unknown Source)
	at my.app.merged.module/org.springframework.boot.SpringApplication.run(Unknown Source)
	at my.app.merged.module/org.springframework.boot.SpringApplication.run(Unknown Source)
	at my.app/com.mycompany.my.app.Main.init(Unknown Source)
	... 3 more
Caused by: org.springframework.cglib.core.CodeGenerationException: java.lang.IllegalAccessException-->module my.app.merged.module does not read module my.app
	at my.app.merged.module/org.springframework.cglib.core.ReflectUtils.defineClass(Unknown Source)
	at my.app.merged.module/org.springframework.cglib.core.AbstractClassGenerator.generate(Unknown Source)
	at my.app.merged.module/org.springframework.cglib.proxy.Enhancer.generate(Unknown Source)
	at my.app.merged.module/org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(Unknown Source)
	at my.app.merged.module/org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(Unknown Source)
	at my.app.merged.module/org.springframework.cglib.core.internal.LoadingCache$2.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at my.app.merged.module/org.springframework.cglib.core.internal.LoadingCache.createEntry(Unknown Source)
	at my.app.merged.module/org.springframework.cglib.core.internal.LoadingCache.get(Unknown Source)
	at my.app.merged.module/org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(Unknown Source)
	at my.app.merged.module/org.springframework.cglib.core.AbstractClassGenerator.create(Unknown Source)
	at my.app.merged.module/org.springframework.cglib.proxy.Enhancer.createHelper(Unknown Source)
	at my.app.merged.module/org.springframework.cglib.proxy.Enhancer.createClass(Unknown Source)
	at my.app.merged.module/org.springframework.context.annotation.ConfigurationClassEnhancer.createClass(Unknown Source)
	at my.app.merged.module/org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(Unknown Source)
	... 15 more
Caused by: java.lang.IllegalAccessException: module my.app.merged.module does not read module my.app
	at java.base/java.lang.invoke.MethodHandles.privateLookupIn(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	... 30 more
```

I tried to fix the problem by adding a `requires 'my.app'` to the `mergedModule` section, but that created a circular dependency.

Any ideas on how to get out of this mess? Thanks!

**Comment by siordache** [comment]
Try this:
```
jlink {
    ...
    launcher {
        ...
        jvmArgs = [
            "--add-reads my.app.merged.module=my.app",
            ...
        ]
    }
}
```

**Comment by gerco** [comment]
Excellent, that works! Thank you. 

Now there are a bunch of other errors that seem mostly related to Spring not being able to autodetect my `@Controller` annotated classes. This is easily fixed by simply adding those explicitly in the Spring config class for the moment.
