### ISSUE TITLE
Merged module created is not found on createDelegatingModules

### ISSUE THREAD

**Issue by utybo** [beryx/badass-jlink-plugin#6]
I do not really why this is happening, but the plugin cannot find the merged module it created when dealing with the createDelegatingModules task.

I do not know if this is important, but this is failing on a dependency that is another project in the multi-project structure I am using in Gradle (`compile project(':bst-java')`)

I am using Windows 10 with the latest Gradle, Java 10 and badass-jlink-plugin versions available.

Here is the jlink configuration from my build.gradle :
```
jlink {
    launcherName = 'openbst'
    moduleName = 'zrrk.bst.openbst'
    mergedModuleName = 'zrrk.bst.dependencies.module'
    mergedModule {
        requires 'java.desktop'
        requires 'javafx.web'
		    requires 'javafx.media'
		    requires 'javafx.swing'
    }
    forceMerge 'log4j'
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
}
```

Here is the relevant logging information from the plugin's tasks :

```
> Task :openbst:prepareMergedJarsDir
Task ':openbst:prepareMergedJarsDir' is not up-to-date because:
  Value of input property 'forceMergedJarPrefixes' has changed for task ':openbst:prepareMergedJarsDir'
taskData: org.beryx.jlink.data.PrepareMergedJarsDirTaskData(forceMergedJarPrefixes:[log4j], mergedJarsDir:C:\ws\BST\openbst\build\jlinkbase\mergedjars, jlinkJarsDirPath:C:\ws\BST\openbst\build/jlinkbase/jlinkjars, nonModularJarsDirPath:C:\ws\BST\openbst\build/jlinkbase/nonmodjars)
modularJars: []
nonModularJars: [findbugs-annotations-3.0.1.jar, log4j-api-2.11.1.jar, log4j-core-2.11.1.jar, miglayout-swing-5.2.jar, miglayout-core-5.2.jar, bst-java-2.0-SNAPSHOT.jar, classindex-3.4.jar, txtmark-0.13.jar, gson-2.8.5.jar, commons-io-2.6.jar, commons-compress-1.18.jar, xz-1.8.jar]
modularJarsRequiredByNonModularJars: []
Copying modular jars required by non-modular jars to C:\ws\BST\openbst\build/jlinkbase/jlinkjars...
Copying mon-modular jars to C:\ws\BST\openbst\build/jlinkbase/nonmodjars...
Merging content into C:\ws\BST\openbst\build\jlinkbase\mergedjars...
:openbst:prepareMergedJarsDir (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 28.771 secs.
:openbst:createMergedModule (Thread[Task worker for ':' Thread 2,5,main]) started.

> Task :openbst:createMergedModule
Task ':openbst:createMergedModule' is not up-to-date because:
  Output property 'mergedModuleJar' file C:\ws\BST\openbst\build\jlinkbase\jlinkjars\zrrk.bst.dependencies.module.jar has been removed.
taskData: org.beryx.jlink.data.CreateMergedModuleTaskData(mergedModuleName:zrrk.bst.dependencies.module, javaHome:C:\Program Files\Java\jdk-10.0.2, mergedModuleInfo:requires java.desktop;
requires javafx.web;
requires javafx.media;
requires javafx.swing;, jdepsEnabled:false, mergedJarsDir:C:\ws\BST\openbst\build\jlinkbase\mergedjars, mergedModuleJar:C:\ws\BST\openbst\build\jlinkbase\jlinkjars\zrrk.bst.dependencies.module.jar, nonModularJarsDirPath:C:\ws\BST\openbst\build/jlinkbase/nonmodjars, jlinkJarsDirPath:C:\ws\BST\openbst\build/jlinkbase/jlinkjars, tmpMergedModuleDirPath:C:\ws\BST\openbst\build/jlinkbase/tmpmerged, tmpModuleInfoDirPath:C:\ws\BST\openbst\build/jlinkbase/tmpmodinfo, tmpJarsDirPath:C:\ws\BST\openbst\build/jlinkbase/tmpjars)
Starting process 'command 'C:\Program Files\Java\jdk-10.0.2/bin/jar''. Working directory: C:\ws\BST\openbst Command: C:\Program Files\Java\jdk-10.0.2/bin/jar --create --file C:\ws\BST\openbst\build/jlinkbase/tmpmerged/zrrk.bst.dependencies.module.jar --no-manifest -C C:\ws\BST\openbst\build\jlinkbase\mergedjars .
Successfully started process 'command 'C:\Program Files\Java\jdk-10.0.2/bin/jar''
Generating module-info in C:\ws\BST\openbst\build\jlinkbase\tmpjars...
Compiling module-info from C:\ws\BST\openbst\build\jlinkbase\tmpjars\org.apache.logging.log4j...
Starting process 'command 'C:\Program Files\Java\jdk-10.0.2/bin/javac''. Working directory: C:\ws\BST\openbst Command: C:\Program Files\Java\jdk-10.0.2/bin/javac -p C:\ws\BST\openbst\build\jlinkbase\tmpmerged;C:\ws\BST\openbst\build/jlinkbase/jlinkjars -d C:\ws\BST\openbst\build\jlinkbase\tmpmodinfo C:\ws\BST\openbst\build\jlinkbase\tmpjars\org.apache.logging.log4j/module-info.java
Successfully started process 'command 'C:\Program Files\Java\jdk-10.0.2/bin/javac''
Copy from C:\ws\BST\openbst\build/jlinkbase/tmpmerged/zrrk.bst.dependencies.module.jar into C:\ws\BST\openbst\build\jlinkbase\jlinkjars\zrrk.bst.dependencies.module.jar...
Insert module-info from C:\ws\BST\openbst\build/jlinkbase/tmpmodinfo into C:\ws\BST\openbst\build\jlinkbase\jlinkjars\zrrk.bst.dependencies.module.jar...
Inserting module-info into C:\ws\BST\openbst\build\jlinkbase\jlinkjars\zrrk.bst.dependencies.module.jar...
Starting process 'command 'C:\Program Files\Java\jdk-10.0.2/bin/jar''. Working directory: C:\ws\BST\openbst Command: C:\Program Files\Java\jdk-10.0.2/bin/jar --update --file C:\ws\BST\openbst\build\jlinkbase\jlinkjars\zrrk.bst.dependencies.module.jar -C C:\ws\BST\openbst\build\jlinkbase\tmpmodinfo module-info.class
Successfully started process 'command 'C:\Program Files\Java\jdk-10.0.2/bin/jar''
:openbst:createMergedModule (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 23.939 secs.
:openbst:createDelegatingModules (Thread[Task worker for ':' Thread 2,5,main]) started.

> Task :openbst:createDelegatingModules
Task ':openbst:createDelegatingModules' is not up-to-date because:
  Task has failed previously.
taskData: org.beryx.jlink.data.CreateDelegatingModulesTaskData(mergedModuleName:zrrk.bst.dependencies.module, javaHome:C:\Program Files\Java\jdk-10.0.2, nonModularJarsDir:C:\ws\BST\openbst\build\jlinkbase\nonmodjars, delegatingModulesDir:C:\ws\BST\openbst\build\jlinkbase\delegating, jlinkJarsDirPath:C:\ws\BST\openbst\build/jlinkbase/jlinkjars, tmpModuleInfoDirPath:C:\ws\BST\openbst\build/jlinkbase/tmpmodinfo, tmpJarsDirPath:C:\ws\BST\openbst\build/jlinkbase/tmpjars)
Creating delegating modules...
Compiling delegate module zrrk.bst.bstjava ...
Starting process 'command 'C:\Program Files\Java\jdk-10.0.2/bin/javac''. Working directory: C:\ws\BST\openbst Command: C:\Program Files\Java\jdk-10.0.2/bin/javac -p C:\ws\BST\openbst\build/jlinkbase/jlinkjars -d C:\ws\BST\openbst\build/jlinkbase/tmpmodinfo C:\ws\BST\openbst\build\jlinkbase\tmpjars\zrrk.bst.bstjava/module-info.java
Successfully started process 'command 'C:\Program Files\Java\jdk-10.0.2/bin/javac''
C:\ws\BST\openbst\build\jlinkbase\tmpjars\zrrk.bst.bstjava\module-info.java:3: error: module not found: zrrk.bst.dependencies.module
    requires transitive zrrk.bst.dependencies.module;
                                             ^
1 error


> Task :openbst:createDelegatingModules FAILED
:openbst:createDelegatingModules (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 6.118 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':openbst:createDelegatingModules'.
> Process 'command 'C:\Program Files\Java\jdk-10.0.2/bin/javac'' finished with non-zero exit value 1

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':openbst:createDelegatingModules'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk-10.0.2/bin/javac'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:395)
        at org.gradle.process.ExecResult$assertNormalExitValue.call(Unknown Source)
        at org.beryx.jlink.impl.CreateDelegatingModulesTaskImpl.createDelegatingModule(CreateDelegatingModulesTaskImpl.groovy:60)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.beryx.jlink.impl.CreateDelegatingModulesTaskImpl$_execute_closure1.doCall(CreateDelegatingModulesTaskImpl.groovy:33)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.beryx.jlink.impl.CreateDelegatingModulesTaskImpl.execute(CreateDelegatingModulesTaskImpl.groovy:32)
        at org.beryx.jlink.impl.CreateDelegatingModulesTaskImpl$execute.call(Unknown Source)
        at org.beryx.jlink.CreateDelegatingModulesTask.createDelegatingModulesAction(CreateDelegatingModulesTask.groovy:74)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more
```

**Comment by siordache** [comment]
Did you push your latest changes to the [f-java10](https://github.com/utybo/BST/tree/f-java10) branch?
If yes, I will use this branch to analyze the problem.

**Comment by utybo** [comment]
Yes, this error is happening on the f-java10 branch (and the latest changes were pushed to it). Feel free to use it to analyze the problem.

**Comment by siordache** [comment]
Your application was not modularized. I added `module-info.java` files to your projects and made a few other adjsutments.
I [created a PR](https://github.com/utybo/BST/pull/15) with my changes.
The unit tests fail now because the Java Module System prevents `getResourceAsStream` to read packages  such as `/utybo/branchingstorytree/api/test/files`. You will need to address yourself this problem by renaming the resources directories or by replacing `getResourceAsStream` with something like `new FileInputStream("src/test/resources/utybo/branchingstorytree/api/test/files/" + path)`.

However, you can successfully execute:
```
gradlew clean build -x test
```
and

```
gradlew clean jlink
```

The last command will create a custom runtime image. You can then start your application by typing:

```
openbst\build\image\bin\openbst.bat
```

**Comment by utybo** [comment]
Thank you very much! I will have a look at your PR as soon as I can

**Comment by siordache** [comment]
I just noticed that my PR contained an unnecessary `doLast` block in openbst/build.gradle.
You can safely [remove it](https://github.com/beryx-gist/BST/commit/f317b9e6c56eb11d04253260abddb9b95e277206).
