### ISSUE TITLE
StackOverflowError on project import

### ISSUE THREAD

**Issue by bjorndarri** [beryx/badass-jlink-plugin#79]
When trying the new 2.15.0 version I ran into a StackOverflowError during project import, seems to be due to  #76 and cyclical project dependencies:

`Cause: java.lang.StackOverflowError
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor144.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.beryx.jlink.util.Util.getAllDependentProjects(Util.groovy:349)
	at org.beryx.jlink.util.Util$_getAllDependentProjects_closure16.doCall(Util.groovy:351)
	at org.beryx.jlink.util.Util$_getAllDependentProjects_closure16.call(Util.groovy)
	at org.beryx.jlink.util.Util.getAllDependentProjects(Util.groovy:351)
	at org.beryx.jlink.util.Util$_getAllDependentProjects_closure16.doCall(Util.groovy:351)
	at org.beryx.jlink.util.Util$_getAllDependentProjects_closure16.call(Util.groovy)
	at org.beryx.jlink.util.Util.getAllDependentProjects(Util.groovy:351)`

I created a minimal project for reproducing the issue:
https://github.com/bjorndarri/badass-jlink-plugin-76-test
where 'core' has a testRuntime dependency on 'model', which has an api dependency on 'core', 'server' then depends on both and triggers the error on project import.

**Comment by siordache** [comment]
Oops! Fixed in 2.15.1.

**Comment by bjorndarri** [comment]
Not an issue in 2.15.1.
