### ISSUE TITLE
Stackoverflow on Java 12 with Gradle 6.0 RC1

### ISSUE THREAD

**Issue by svenreimers** [beryx/badass-jlink-plugin#95]
Trying to use jpackage running Gradle 6.0 RC1 on top of Java 12 results in Stackoverflow
`	at org.beryx.jlink.data.JlinkPluginExtension.toString(JlinkPluginExtension.groovy)
	at org.gradle.internal.instantiation.generator.ManagedObjectFactory$ManagedPropertyName.getDisplayName(ManagedObjectFactory.java:137)
	at org.gradle.internal.instantiation.generator.ManagedObjectFactory$ManagedPropertyName.toString(ManagedObjectFactory.java:126)
	at org.gradle.api.internal.provider.AbstractProperty.toString(AbstractProperty.java:76)
	at org.beryx.jlink.data.JlinkPluginExtension.toString(JlinkPluginExtension.groovy)
	at org.gradle.internal.instantiation.generator.ManagedObjectFactory$ManagedPropertyName.getDisplayName(ManagedObjectFactory.java:137)
	at org.gradle.internal.instantiation.generator.ManagedObjectFactory$ManagedPropertyName.toString(ManagedObjectFactory.java:126)
	at org.gradle.api.internal.provider.AbstractProperty.toString(AbstractProperty.java:76)
	at org.beryx.jlink.data.JlinkPluginExtension.toString(JlinkPluginExtension.groovy)
	at org.gradle.internal.instantiation.generator.ManagedObjectFactory$ManagedPropertyName.getDisplayName(ManagedObjectFactory.java:137)
	at org.gradle.internal.instantiation.generator.ManagedObjectFactory$ManagedPropertyName.toString(ManagedObjectFactory.java:126)
	at org.gradle.api.internal.provider.AbstractProperty.toString(AbstractProperty.java:76)
`

**Comment by msgilligan** [comment]
See https://github.com/ConsensusJ/wallet-framework/pull/6 for the changes necessary to upgrade my **wallet-framework** build to Gradle 6.0 RC1. You can also see the failed build on Github Actions, here:
https://github.com/ConsensusJ/wallet-framework/runs/267048450

**Comment by siordache** [comment]
Fixed in 2.16.2.

**Comment by msgilligan** [comment]
https://github.com/ConsensusJ/wallet-framework is now building jpackages with BA Jlink Plugin 2.16.2, Gradle 6.0 RC1, and JDK 13.

**Comment by siordache** [comment]
Thanks for the feedback! Closing.

**Comment by msgilligan** [comment]
@siordache I just bumped my build to Gradle 6.0-RC-2 and it seems good: 
https://github.com/ConsensusJ/wallet-framework/commit/8b5f4e8f944c509b94489921dfaef4c2ae8f80d2
